### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by aurasphere** [gilyes/pi-shutdown#3]
Hey @gilyes thanks for your work, this script saved my life! I wanted to fork this repo and publish some tweaks I made to it but I noticed there's no license on this repo. I was wondering if this is intended or just an overlook. Basically, (according to [GitHub guidelines](https://help.github.com/en/articles/licensing-a-repository#what-happens-if-i-dont-choose-a-license)) this would mean that your code is private and can't be modified.

Also, I'm willing to share them with a pull request if you are interested. The edits are:
 - configuration for the type of button (normally closed or normally open)
 - removed the busy waiting loop and used signal.pause() instead 
 - configured the script as a service
 - created an install script for the service

Please let me know if I can publish my changes without problems (this will require you to put a license file) on my own repo and if you want me to open a pull request. Thanks again!

**Comment by gilyes** [comment]
@aurasphere, added a license file. 

Those sound like great changes but I don't really have time to maintain this repo so best is probably to just continue on your fork. Good luck!

**Comment by aurasphere** [comment]
Ok, thank you very much!
